services:
  mysql:
    image: mysql:8.4
    container_name: anniesmassages-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: anniesmassages
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password@123!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
